# Generated by Django 4.1.5 on 2023-01-29 09:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='rasmlar/playlist_rasm')),
                ('about', ckeditor.fields.RichTextField()),
                ('count', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoDars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150)),
                ('izoh', ckeditor.fields.RichTextField()),
                ('video', models.FileField(upload_to='video_darslar/video')),
                ('playlisti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.playlist')),
            ],
        ),
    ]
